[workspace]
resolver = "2"

members = [
  "actors/*",
  "interfaces/*/rust",
 # "capability_providers/*",
]

default-members = [
  "actors/*",
  "interfaces/*/rust",
 # "capability_providers/*",
]
exclude = ["ui/rust_new","capability_providers"]


[profile.release]
# Optimize for small code size
#opt-level = "s"
#lto = true
debug = true

[patch.crates-io]
instant = {path="wasmcloud_patches/instant"}
getrandom = {path="wasmcloud_patches/getrandom"}
#bevy_app = {path="wasmcloud_patches/bevy_app"}
wasmbus-macros= {git ="https://github.com/wasmCloud/weld", rev="84b71217e9a88b7dd76378715d422da1b5f874c4"}

[patch."https://github.com/bevyengine/bevy"]
bevy_app = {path="wasmcloud_patches/bevy_app"}
