[workspace]

members = [
  "actors/*",
  "interfaces/*/rust",
  "capability_providers/*",
]

default-members = [
  "actors/*",
  "interfaces/*/rust",
  "capability_providers/*",
]
[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true