[package]
name = "qq_party_shared"
version = "0.1.0"
authors = ["ostwilkens <carl@ostwilkens.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
actor = ["bevy_ecs_wasm"]
non_actor = ["bevy_ecs"]

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
bevy_ecs_wasm = {git = "https://github.com/alanpoon/bevy-ecs-wasm06",optional = true}
bevy_ecs = { git = "https://github.com/bevyengine/bevy", default-features = false,optional = true}
bevy_math = {git = "https://github.com/bevyengine/bevy"}
bevy_log = {git = "https://github.com/bevyengine/bevy"}