[package]
name = "qq_party_shared"
version = "0.1.0"
authors = ["ostwilkens <carl@ostwilkens.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
actor = ["bevy_ecs_wasm"]
non_actor = ["bevy_ecs"]

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
bevy_ecs_wasm = {git = "https://github.com/UnlimitedHugs/bevy-ecs-wasm",optional = true}
bevy_ecs = { version = "0.6", default-features = false,optional = true}
bevy_math = {version = "0.6"}