[*] --> httproom
httproom --> html
[*] --> socket
socket --> OnMessagejoinroom
OnMessagejoinroom --> broadcast: user-connected
ws_server : process user
ws_server --> ingame_bean
ingame_bean : room_gift
ws_server --> room_message
ws_server --> room_streaming
@enduml