[package]
name = "game_logic2"
version = "0.1.0"
authors = ["alanpoon"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasmbus-rpc = "0.8.2"
async-trait = "0.1"
serde_bytes = "0.11"
serde = { version = "1.0.123", features = ["derive"]}
serde_json = "1.0.64"
futures = "0.3"
wasmcloud-interface-logging = "0.5.0"
wasmcloud-interface-messaging = "0.5.0"
wasmcloud-interface-thread = { path = "../../interfaces/thread/rust"}
convert_case = "0.1.0"
bevy_math = {version = "0.6.0"}
lazy_static = "1.4.0"
qq_party_shared = {path = "../../qq_party_shared" , features = ["actor"]}
bevy_app = {version = "0.6.0",default-features = false}
bevy_utils = {version = "0.6.0",default-features = false}
bevy_ecs = {version = "0.6.0",default-features = false}
instant = "0.1.12"