
version: "4"
services:
  wasmcloud:
    deploy:
        resources:
          limits:
            cpus: '0.5'
    image: wasmcloud/wasmcloud_host:0.63.0
    environment:
      RUST_LOG: debug,hyper=info
      WASMCLOUD_RPC_HOST: 172.17.0.1
      WASMCLOUD_CTL_HOST: 172.17.0.1
      WASMCLOUD_PROV_RPC_HOST: 172.17.0.1
      WASMCLOUD_HOST_SEED: SNAKDMBLB7TPIL4K3YXDGLUDXYFEEB2UAUXSAJYFBUKAWXBT6VPSTSE34Y
      WASMCLOUD_CLUSTER_SEED: SCALV3N2M5JRUOCSLTRTAIQYJSBKNZ3XMGME2XI3L3OSR2RRSYUTMHAN7E
      WASMCLOUD_OCI_ALLOWED_INSECURE: 172.17.0.1:5000
#      OTEL_TRACES_EXPORTER: otlp
#      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:55681
    ports:
      - "4000:4000"
      - "8080-8089:8080-8089" # Allows exposing examples on ports 8080-8089
    #command: sh -c "curl -v -X GET http://host.docker.internal:5000/v2/_catalog"
  nats:
    image: nats:2.8.4-alpine
    ports:
      - "4222:4222"
      - "7083:7083"
    volumes:
      - /home/ubuntu/qq_party/ops/websocket2new.conf:/etc/nats/nats-server.conf
      - /home/ubuntu/certs_namespace/:/root/certs_namespace
    command: [ "-js" ,"-c","/etc/nats/nats-server.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
  # wadm:
  #   depends_on:
  #     - "redis"
  #   image: wasmcloud.azurecr.io/wadm:0.1.0
  #   environment:
  #     - WADM_NATS_HOST=host.docker.internal
  #     - WADM_REDIS_HOST=redis