name: qq_party

on:
  push:
    branches: [release]
  pull_request:
    branches: [main]

jobs:
  build_cap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install wash-cli
      #- run: curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash && sudo apt install wash
      - run: which wash
      - run: wash --version
      - run: mkdir capability_providers/game-provider/build
      - run: cd capability_providers/game-provider && make && ls build
      - run: ls capability_providers/game-provider/build
      - uses: actions/upload-artifact@v3
        with:
          path: capability_providers/game-provider/build/game-provider.par.gz
      